version: '2'

services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
        - "8000:8000"
    volumes:
        - ./application:/application
        - ./config/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile-php7-fpm
    volumes:
        - ./application:/application
        # - amynfs:/dockerdir

# volumes:
#   amynfs:
#     driver: local
#     driver_opts:
#       type: "nfs"
#       o: "addr=10.0.33.99,nolock,hard,rw"
#       device: ":./docker"