version: '2'

services:
  web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./application:/application
        - ./config/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile-php7-fpm
    volumes:
        - ./application:/application
